[package]
name = "agentic-guest"
version = "0.0.1"
edition = "2024"

[workspace]

[profile.release]
opt-level = "s"
lto = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = ["http", "logging"]
http = ["dep:reqwest"]
logging = ["dep:log", "dep:wasi-logger"]

[dependencies]
# Core dependencies
rquickjs = { version = "0.9.0", default-features = false, features = ["futures", "bindgen", "loader", "macro"] }

encoding_rs = "0.8.35"
futures = { version = "0.3.31", features = [] }
futures-concurrency = "7.6.3"
pin-project = "1.1.10"
wasi = "0.12.1+wasi-0.2.0"
wasi-async-runtime = "0.1.2"
wit-bindgen-rt = { version = "0.42.1", features = ["bitflags"] }

# HTTP
reqwest = { git = "https://github.com/golemcloud/reqwest", branch = "update-july-2025", features = ["async"], optional = true }

# Logging
log = { version = "0.4.22", default-features = false, optional = true }
wasi-logger = { version = "0.1.2", default-features = false, optional = true }

[package.metadata.component.bindings]
ownership = "owning"

[package.metadata.component.target]
path = "wit-generated"

[package.metadata.component.target.dependencies]
"wasi:io" = { path = "wit-generated/deps/io" }
"wasi:clocks" = { path = "wit-generated/deps/clocks" }
"golem:rpc" = { path = "wit-generated/deps/golem-rpc" }
"golem:agent" = { path = "wit-generated/deps/golem-agent" }
"golem:api" = { path = "wit-generated/deps/golem-1.x" }
"golem:agentic-guest-exports" = { path = "wit-generated/deps/golem_agentic-guest-exports" }
"golem:durability" = { path = "wit-generated/deps/golem-durability" }
"golem:rdbms" = { path = "wit-generated/deps/rdbms" }
"unused:main" = { path = "wit-generated/deps/all" }
"wasi:blobstore" = { path = "wit-generated/deps/blobstore" }
"wasi:filesystem" = { path = "wit-generated/deps/filesystem" }
"wasi:sockets" = { path = "wit-generated/deps/sockets" }
"wasi:random" = { path = "wit-generated/deps/random" }
"wasi:cli" = { path = "wit-generated/deps/cli" }
"wasi:config" = { path = "wit-generated/deps/config" }
"wasi:http" = { path = "wit-generated/deps/http" }
"wasi:keyvalue" = { path = "wit-generated/deps/keyvalue" }
"wasi:logging" = { path = "wit-generated/deps/logging" }
